#
# Try to find SOIL library and include path.
# Once done this will define
#
# SOIL_FOUND
# SOIL_INCLUDE_DIR
# SOIL_INCLUDE_DIRS
# SOIL_LIBRARY
# SOIL_LIB_DIRS

if(NOT SOIL_FOUND)

    FIND_PATH(SOIL_INCLUDE_DIR SOIL.h
  PATHS
  ${PROJECT_SOURCE_DIR}/ext/SOIL/src/
    NO_DEFAULT_PATH
    )

FIND_PATH( SOIL_LIB_DIRS libSOIL.a
  PATHS
  ${PROJECT_SOURCE_DIR}/ext/SOIL/lib/
    NO_DEFAULT_PATH
    )

FIND_LIBRARY( SOIL_LIBRARY NAMES SOIL
  PATHS
  ${PROJECT_SOURCE_DIR}/ext/SOIL/lib/
    NO_DEFAULT_PATH
    )

SET(SOIL_FOUND "NO")

IF (SOIL_INCLUDE_DIR AND SOIL_LIBRARY)
    SET(SOIL_FOUND "YES")
ENDIF (SOIL_INCLUDE_DIR AND SOIL_LIBRARY)

if(SOIL_FOUND)
  message(STATUS "Found SOIL: ${SOIL_INCLUDE_DIR}")
else(SOIL_FOUND)
  if (NOT SOIL_FIND_QUIETLY)
    message(FATAL_ERROR "could NOT find SOIL")
  endif (NOT SOIL_FIND_QUIETLY)
endif(SOIL_FOUND)

endif(NOT SOIL_FOUND)
